### ISSUE TITLE
Second tag throws an error

### ISSUE THREAD

**Issue by temecom** [samueltbrown/gradle-cucumber-plugin#26]
When I use a second ANDed tag in the tags parameter as in: 

```
tags = ['@DUC', '@development']
```

an exception is thrown. A single tag works fine. 

Exception: 
- What went wrong:
  Execution failed for task ':duc:plum-duc-test-parent:plum-duc-tests:cucumber'.
  
  > Not a file or directory: C:\p4\nemo\plum720\sw\01.0\dev\baseline\test\duc\plum-duc-test-parent\plum-duc-tests\@development
- Try:
  Run with --info or --debug option to get more log output.
- Exception is:
  org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':duc:plum-duc-test-parent:plum-duc-tests:cucumber'.
      at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
      at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
      at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
      at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
      at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
      at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
      at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
      at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
      at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
      at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:289)
      at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
      at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
      at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
      at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
      at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:86)
      at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
      at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:61)
      at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
      at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:67)
      at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
      at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:61)
      at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:54)
      at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:166)
      at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:113)
      at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:81)
      at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:64)
      at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
      at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
      at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:35)
      at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
      at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:50)
      at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
      at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:201)
      at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:174)
      at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:170)
      at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:139)
      at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
      at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
      at org.gradle.launcher.Main.doAction(Main.java:46)
      at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
      at org.gradle.launcher.Main.main(Main.java:37)
      at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:50)
      at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:32)
      at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
  Caused by: java.lang.IllegalArgumentException: Not a file or directory: C:\p4\nemo\plum720\sw\01.0\dev\baseline\test\duc\plum-duc-test-parent\plum-duc-tests\@development
      at cucumber.runtime.io.FileResourceIterator$FileIterator.<init>(FileResourceIterator.java:54)
      at cucumber.runtime.io.FileResourceIterator.<init>(FileResourceIterator.java:20)
      at cucumber.runtime.io.FileResourceIterable.iterator(FileResourceIterable.java:19)
      at cucumber.runtime.model.CucumberFeature.load(CucumberFeature.java:51)
      at cucumber.runtime.model.CucumberFeature.load(CucumberFeature.java:33)
      at cucumber.runtime.RuntimeOptions.cucumberFeatures(RuntimeOptions.java:143)
      at cucumber.runtime.Runtime.run(Runtime.java:107)
      at cucumber.api.cli.Main.run(Main.java:26)
      at cucumber.api.cli.Main.main(Main.java:16)
      at com.excella.gradle.cucumber.CucumberRunner.runCucumberTests(CucumberRunner.java:74)
      at com.excella.gradle.cucumber.CucumberRunner$runCucumberTests.call(Unknown Source)
      at com.excella.gradle.cucumber.tasks.CucumberTask.executeCucumberRunner(CucumberTask.groovy:122)
      at com.excella.gradle.cucumber.tasks.CucumberTask.cucumber(CucumberTask.groovy:50)
      at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
      at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:219)
      at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:212)
      at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:201)
      at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:533)
      at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:516)
      at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
      at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
      ... 43 more

**Comment by gregmunt** [comment]
Is this still an issue?
